
// A 2D texture fitting the window size (i.e. the display texture);
// carries the multi-frame image data generated by [SceneVis]
Texture2D<float4> displayTex : register(t0);

// A texture sampler; needed to cleanly sample values from the
// display texture in [t0]
SamplerState wrapSampler : register(s0);

struct Pixel
{
    float4 pos : SV_POSITION0;
    float2 texCoord : TEXCOORD0;
};

float4 main(Pixel pixIn) : SV_TARGET
{
    //...perform denoising/post-filtering here...
    // Pass the filtered screen texture into the display :)
    return displayTex.Sample(wrapSampler, pixIn.texCoord);
}